// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

import "../../public/assets/css/style.css"; 

import Header from "./components/common/Header/Header";
import Footer from "./components/common/Footer/Footer";


export const metadata: Metadata = {
  title: "Nexon Paints",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="/css/style.css" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"
        />
        <link
          rel="icon"
          href={`${process.env.BASE_URL || ''}/assets/img/favicon.ico`}
        />
      </head>
      <body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60" className="antialiased">
        <Header />
        {children}
        <Footer />

        {/* External Scripts */}
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" />
        <Script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" />
        <Script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js" />
        <Script src={`${process.env.BASE_URL || ''}/assets/js/main.js`} strategy="afterInteractive" />
       

      </body>
    </html>
  );
}
