// app/layout.tsx

import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

import Header from "./components/common/Header/Header";
import Footer from "./components/common/Footer/Footer";
import BlockJQueryCDN from "./components/BlockJQueryCDN";

export const metadata: Metadata = {
  title: "Nexon Paints",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    icon: "/assets/images/favicon.ico", // ✅ Correct favicon instead of CSS
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Google Fonts */}
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />

        {/* Bootstrap CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
        {/* Custom Styles */}
        <link
          rel="stylesheet"
          href={`${process.env.NEXT_PUBLIC_BASE_PATH || ""}/assets/css/style.css`}
        />

        {/* Swiper CSS (only keep one) */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css"
        />

        {/* Slick Carousel CSS */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"
        />

        {/* Inline helper styles */}
        <style>{`
          .bx { position: relative; overflow: hidden; }
          .topup1 { position: fixed; bottom: 24px; right: 24px; z-index: 9999; display: none; }
          .topup1.show { display: block; }
          .textcenter { text-align: center; }
          .container-fluid { width: 100%; }
        `}</style>
      </head>
      <body
        id="myPage"
        data-bs-spy="scroll"
        data-bs-target=".navbar"
        data-bs-offset="60" 
        suppressHydrationWarning
      >
        <BlockJQueryCDN />
        <Header />
        {children}
        <Footer />

        {/* External Scripts */}
        <Script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js" strategy="beforeInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js" strategy="afterInteractive" />
        <Script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js" />
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" />
        <Script
          src={`${process.env.NEXT_PUBLIC_BASE_PATH || ""}/assets/js/main.js`}
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
